apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-src-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: php-src-pv  # Reference the PV you just created

