apiVersion: v1
kind: PersistentVolume
metadata:
  name: php-src-pv
spec:
  capacity:
    storage: 1Gi  # Adjust to your needs
  accessModes:
    - ReadWriteMany  # Allow both Nginx and PHP to access
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/abdelrahman/LEMP_STACK_DOCKERIZED/php/src
    type: Directory

